### ISSUE TITLE
Conversion BOOL -> YAO

### ISSUE THREAD

**Issue by david-k** [encryptogroup/ABY#102]
Hi,
I have the following circuit:

    std::vector<Sharing*>& sharings = party->GetSharings();
    BooleanCircuit *aby_yao = dynamic_cast<BooleanCircuit*>(sharings.at(e_sharing::S_YAO)->GetCircuitBuildRoutine());
    BooleanCircuit *aby_bool = dynamic_cast<BooleanCircuit*>(sharings.at(e_sharing::S_BOOL)->GetCircuitBuildRoutine());
    
    uint32_t const_one_yao = aby_yao->PutConstantGate(1);
    uint32_t const_zero_yao = aby_yao->PutINVGate(const_one_yao);
    uint32_t const_zero_gmw = aby_yao->PutY2BCONVGate(const_zero_yao);
    aby_bool->PutOUTGate(const_zero_gmw, ALL);
    
    party->ExecCircuit();

Is this correct? Because during execution, I get the following error:

    YaoClientSharing: Non-interactive operation not recognized: 7(Conversion)

**Comment by dd23** [comment]
The conversion gates must be called from a circuit of the _target_ sharing (see 3.3 in the developer guide).

So if you call `uint32_t const_zero_gmw = aby_bool->PutY2BCONVGate(const_zero_yao);` (`aby_bool` instead of  `aby_yao`) the error should disappear.

Please give it a try and let us know if that worked.

**Comment by david-k** [comment]
Yes, this works. Sorry and thank you!

**Comment by dd23** [comment]
No worries. Glad I could help :)
