### ISSUE TITLE
Strings comparison

### ISSUE THREAD

**Issue by prvsousa** [encryptogroup/ABY#11]
Hello,

I'm thinking in make the TODO related with the use strings in the library, someone can give me guidance regarding this topic? Is the project owner interested in such evolution?

**Comment by dd23** [comment]
I'm sorry, I'm not exactly sure what you mean. Could you please explain?

**Comment by prvsousa** [comment]
I want to make comparison between strings and I see that you only support "numbers" .

**Comment by dd23** [comment]
I assume you're referring to something like [PutEQGate](https://github.com/encryptogroup/ABY/blob/public/src/abycore/circuit/booleancircuits.cpp#L1493) that checks two values for equality. If so, string comparison is already possible.

In that case it does not matter if you compare "numbers", strings or something else because in the end bits will be mapped to wires, which are compared.

So to check equality of strings you would input the strings, probably using something like `string.c_str()` and the appropriate bit lengths for the input gate and then input these shares in the the EQ gate.

**Comment by prvsousa** [comment]
Instead of this I use the millionaire's problem and instead compare if >= , <= , I check the equality. This is correct?

**Comment by dd23** [comment]
Yes, that would be one option and should work.

**Comment by patricia93sousa** [comment]
but I make the equality with "==" instead of the function PutEQGate, but in this case as the sharing of values is made before I think that is secure right?!

**Comment by patricia93sousa** [comment]
I explain me bad... x) I use PutEQGate instead of the PutGTGate , but for the response, it is complicated for me understand: 

> cout << "\nVerify Result: \t" << ((alice_money > bob_money) ? ALICE : BOB)
> 				<< "\n";

this line of your code, it is confused, because you use PutGTGate but then, you make the comparison with ">".
