### ISSUE TITLE
Error when runnning millionaire_prob

### ISSUE THREAD

**Issue by hrmsk** [encryptogroup/ABY#148]
When we tried running the millionaire_prob, the output of the two terminals is different.

computer1
$ ./millionaire_prob_test -r 0
Alice Money:	1138252582
Bob Money:	1699263743
Circuit Result:	ALICE
Verify Result: 	BOB

computer2
$ ./millionaire_prob_test -r 1
Alice Money:	2062001301
Bob Money:	2016898929
Circuit Result:	ALICE
Verify Result: 	ALICE

Any help would be appreciated.

**Comment by ellio0ott** [comment]
It's because each side generates two random numbers. If you execute two terminals in a very (very) small time interval it will work. But twisting the code a little bit you can write one script for the Garbler, one for the Evaluator and the results will be consistent. Please close if you're ok with the answer.
