### ISSUE TITLE
PutBarrelRightShifterGate Problem

### ISSUE THREAD

**Issue by akappy7** [encryptogroup/ABY#34]
Hi, I was having problem getting the PutBarrelRightShifterGate work as expected. I set a number share to 110 and shift share to 1 and passed those to the BooleanCircuit PutBarrelRightShifterGate function.  The expected result was 11 from the output but the result received was 220. 

Both shares were uint8_t. I added a screenshot of the code I am referring to. My question is, is that correct behavior and I am misinterpreting the functionality? Thank you in advance. 

![image](https://user-images.githubusercontent.com/7969631/36703279-cdb777a8-1b0f-11e8-9119-bcdefa93c9ea.png)

**Comment by Oleksandr-Tkachenko** [comment]
Hi,

the Barrel Shifter gate works indeed as expected. Since ABY internally uses big-endian representation (C/C++ uses little-endian), PutRightBarrelShifter(<110>, <1>) = 110 << 1 =  0x6E << 1 = 220 = 0xDC. Furthermore, shifting the value 110 you would get neither 11 nor 1100 because these are decimal numbers and values are shifted bit-wise. For this purpose, I would suggest using the more intuitive hexadecimal representation, i.e., 0x6E for the decimal 110 and 0x06 for the binary 110. Another possibility is also to use the binary representation in C++17 as 0b0000'0110 which, however, has to 
be first enabled in the compiler.

P.S.: to prevent confusion because of the changing endianness, I will switch left and right shift functions, so the shifting logic will be the same as in C.

Best,
Alex

**Comment by akappy7** [comment]
Thank you for the response. Closing the issue.

**Comment by akappy7** [comment]
I believe line 3144 of src/abycore/circuit/booleancircuits.cpp should be:

`vector<uint32_t> res = PutBarrelLeftShifterGate(wires, n);`

instead of: 

`vector<uint32_t> res = PutBarrelRightShifterGate(wires, n);`

Also, would it be possible to give an example of a PutBarrelRightShifterGate with the new implementation? (Maybe using the same values of 110 and 1).  I expect 55 to be the result but that is not the result I am seeing. I am getting "3959422976".

**Comment by Oleksandr-Tkachenko** [comment]
Thanks for pointing this out. The way you are using ABY is correct. The problem was a bug in this function. It should work fine now. Please try out the new version and if you will face any problems, just let me know.
